"""empty message

Revision ID: 506640fd22f5
Revises: 5d1b74a777bd
Create Date: 2019-03-21 14:18:12.160138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506640fd22f5'
down_revision = '5d1b74a777bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_connections',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('server', sa.String(length=100), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('database', sa.String(length=100), nullable=True),
    sa.Column('login', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('additionalparams', sa.String(length=100), nullable=True),
    sa.Column('system_type', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_connections')
    # ### end Alembic commands ###
