"""empty message

Revision ID: 5d1b74a777bd
Revises: 96b95e9e6531
Create Date: 2019-02-20 13:59:09.388153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1b74a777bd'
down_revision = '96b95e9e6531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'active')
    # ### end Alembic commands ###
